### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by NoahTwine** [missinglink/supervisord#2]
When trying to pull down this repository via composer I persistently get the following error:

"Your requirements could not be resolved to an installable set of packages."

Any ideas on why this might be? I have the build settings set to @dev.

**Comment by missinglink** [comment]
I haven't touched it for years, it worked when I last tried it back then. Would you like to take over?

**Comment by missinglink** [comment]
Are you following the install steps from here? https://github.com/missinglink/supervisord/blob/master/install.sh

**Comment by NoahTwine** [comment]
@missinglink Thanks for the info, Peter. We seem to have got it working now.

Can't take over the repo with the my schedule just yet. But thanks anyway.
